apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom-deployment
  namespace: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      containers:
        - name: kubedoom
          image: storaxdev/kubedoom:0.5.0
          ports:
            - name: vnc
              containerPort: 5900
              protocol: TCP
          securityContext:
            privileged: true
      hostNetwork: true
  strategy:
    type: Recreate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedoom
  namespace: kubedoom
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedoom
subjects:
  - kind: ServiceAccount
    name: kubedoom
    namespace: kubedoom
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
